export interface MinifigureTheme {
  readonly id: string;
  readonly name: string;
  readonly skinColor: string;
  readonly headgearType: string;
  readonly headgearColor: string;
  readonly headgearAccentColor?: string;
  readonly torsoColor: string;
  readonly armColor: string;
  readonly handColor: string;
  readonly hipsColor: string;
  readonly legsColor: string;
  readonly feetColor?: string;
  readonly torsoDecalType: string;
  readonly faceType: string;
  readonly accessoryType?: string;
}

export const DEFAULT_MINIFIGURE_THEME: MinifigureTheme = {
  id: 'classic-minifig',
  name: 'Classic Minifig',
  skinColor: '#F7CA18',
  headgearType: 'classic-hair',
  headgearColor: '#78350F',
  torsoColor: '#DC2626',
  armColor: '#DC2626',
  handColor: '#F7CA18',
  hipsColor: '#1E3A8A',
  legsColor: '#2563EB',
  torsoDecalType: 'classic-smile-print',
  faceType: 'classic-smile'
};

export const MINIFIGURE_THEMES: Readonly<Record<string, MinifigureTheme>> = {
  'dinosaur-minifig': {
    id: 'dinosaur-minifig',
    name: 'Dinosaur Minifig',
    skinColor: '#F7CA18',
    headgearType: 'dino-cowl',
    headgearColor: '#16A34A',
    headgearAccentColor: '#86EFAC',
    torsoColor: '#16A34A',
    armColor: '#15803D',
    handColor: '#15803D',
    hipsColor: '#166534',
    legsColor: '#16A34A',
    feetColor: '#14532D',
    torsoDecalType: 'dino-scales',
    faceType: 'classic-smile'
  },
  'ninja-minifig': {
    id: 'ninja-minifig',
    name: 'Ninja Minifig',
    skinColor: '#F7CA18',
    headgearType: 'ninja-cowl',
    headgearColor: '#1F2937',
    headgearAccentColor: '#DC2626',
    torsoColor: '#111827',
    armColor: '#1F2937',
    handColor: '#1F2937',
    hipsColor: '#DC2626',
    legsColor: '#111827',
    torsoDecalType: 'ninja-tunic',
    faceType: 'ninja-focus'
  },
  'king-minifig': {
    id: 'king-minifig',
    name: 'King Minifig',
    skinColor: '#F7CA18',
    headgearType: 'crown',
    headgearColor: '#F59E0B',
    headgearAccentColor: '#EF4444',
    torsoColor: '#991B1B',
    armColor: '#B91C1C',
    handColor: '#F7CA18',
    hipsColor: '#D97706',
    legsColor: '#7F1D1D',
    torsoDecalType: 'king-ermine',
    faceType: 'king-beard'
  },
  'jester-minifig': {
    id: 'jester-minifig',
    name: 'Jester Minifig',
    skinColor: '#F7CA18',
    headgearType: 'jester-hat',
    headgearColor: '#7C3AED',
    headgearAccentColor: '#F59E0B',
    torsoColor: '#8B5CF6',
    armColor: '#F59E0B',
    handColor: '#F7CA18',
    hipsColor: '#6D28D9',
    legsColor: '#7C3AED',
    torsoDecalType: 'jester-diamonds',
    faceType: 'jester-grin'
  },
  'samurai-minifig': {
    id: 'samurai-minifig',
    name: 'Samurai Minifig',
    skinColor: '#F7CA18',
    headgearType: 'samurai-kabuto',
    headgearColor: '#1E293B',
    headgearAccentColor: '#F59E0B',
    torsoColor: '#0F172A',
    armColor: '#1E293B',
    handColor: '#F7CA18',
    hipsColor: '#991B1B',
    legsColor: '#0F172A',
    torsoDecalType: 'samurai-armor',
    faceType: 'samurai-mustache'
  },
  'astronaut-minifig': {
    id: 'astronaut-minifig',
    name: 'Astronaut Minifig',
    skinColor: '#F7CA18',
    headgearType: 'astronaut-helmet',
    headgearColor: '#2563EB',
    torsoColor: '#2563EB',
    armColor: '#1D4ED8',
    handColor: '#F7CA18',
    hipsColor: '#1D4ED8',
    legsColor: '#2563EB',
    torsoDecalType: 'classic-space',
    faceType: 'classic-smile'
  },
  'wizard-minifig': {
    id: 'wizard-minifig',
    name: 'Wizard Minifig',
    skinColor: '#F7CA18',
    headgearType: 'wizard-hat',
    headgearColor: '#6D28D9',
    headgearAccentColor: '#FBBF24',
    torsoColor: '#5B21B6',
    armColor: '#6D28D9',
    handColor: '#F7CA18',
    hipsColor: '#D97706',
    legsColor: '#4C1D95',
    torsoDecalType: 'wizard-stars',
    faceType: 'wizard-beard'
  },
  'robot-minifig': {
    id: 'robot-minifig',
    name: 'Cyber Robot Minifig',
    skinColor: '#94A3B8',
    headgearType: 'robot-cap',
    headgearColor: '#64748B',
    headgearAccentColor: '#06B6D4',
    torsoColor: '#475569',
    armColor: '#64748B',
    handColor: '#94A3B8',
    hipsColor: '#334155',
    legsColor: '#475569',
    torsoDecalType: 'robot-circuits',
    faceType: 'robot-visor'
  },
  'knight-minifig': {
    id: 'knight-minifig',
    name: 'Royal Knight Minifig',
    skinColor: '#F7CA18',
    headgearType: 'knight-helmet',
    headgearColor: '#94A3B8',
    headgearAccentColor: '#DC2626',
    torsoColor: '#CBD5E1',
    armColor: '#94A3B8',
    handColor: '#F7CA18',
    hipsColor: '#1E40AF',
    legsColor: '#64748B',
    torsoDecalType: 'knight-shield',
    faceType: 'classic-smile'
  },
  'pirate-minifig': {
    id: 'pirate-minifig',
    name: 'Pirate Minifig',
    skinColor: '#F7CA18',
    headgearType: 'pirate-tricorn',
    headgearColor: '#18181B',
    headgearAccentColor: '#F43F5E',
    torsoColor: '#DC2626',
    armColor: '#18181B',
    handColor: '#F7CA18',
    hipsColor: '#78350F',
    legsColor: '#92400E',
    torsoDecalType: 'pirate-stripes',
    faceType: 'pirate-patch'
  },
  'superhero-minifig': {
    id: 'superhero-minifig',
    name: 'Superhero Minifig',
    skinColor: '#F7CA18',
    headgearType: 'superhero-mask',
    headgearColor: '#1E293B',
    torsoColor: '#2563EB',
    armColor: '#2563EB',
    handColor: '#DC2626',
    hipsColor: '#F59E0B',
    legsColor: '#1D4ED8',
    feetColor: '#DC2626',
    torsoDecalType: 'superhero-crest',
    faceType: 'classic-smile',
    accessoryType: 'superhero-cape'
  },
  'detective-minifig': {
    id: 'detective-minifig',
    name: 'Detective Minifig',
    skinColor: '#F7CA18',
    headgearType: 'deerstalker',
    headgearColor: '#B45309',
    headgearAccentColor: '#78350F',
    torsoColor: '#D97706',
    armColor: '#B45309',
    handColor: '#F7CA18',
    hipsColor: '#78350F',
    legsColor: '#92400E',
    torsoDecalType: 'trenchcoat-tie',
    faceType: 'samurai-mustache'
  },
  'chef-minifig': {
    id: 'chef-minifig',
    name: 'Chef Minifig',
    skinColor: '#F7CA18',
    headgearType: 'chef-toque',
    headgearColor: '#F8FAFC',
    torsoColor: '#FFFFFF',
    armColor: '#F1F5F9',
    handColor: '#F7CA18',
    hipsColor: '#334155',
    legsColor: '#1E293B',
    torsoDecalType: 'chef-buttons',
    faceType: 'samurai-mustache'
  },
  'firefighter-minifig': {
    id: 'firefighter-minifig',
    name: 'Firefighter Minifig',
    skinColor: '#F7CA18',
    headgearType: 'fire-helmet',
    headgearColor: '#EAB308',
    headgearAccentColor: '#DC2626',
    torsoColor: '#1F2937',
    armColor: '#111827',
    handColor: '#EAB308',
    hipsColor: '#111827',
    legsColor: '#1F2937',
    torsoDecalType: 'firefighter-stripes',
    faceType: 'soot-smudge'
  },
  'diver-minifig': {
    id: 'diver-minifig',
    name: 'Deep Sea Diver Minifig',
    skinColor: '#F7CA18',
    headgearType: 'diving-helmet',
    headgearColor: '#D97706',
    headgearAccentColor: '#38BDF8',
    torsoColor: '#0284C7',
    armColor: '#0369A1',
    handColor: '#D97706',
    hipsColor: '#075985',
    legsColor: '#0284C7',
    feetColor: '#78350F',
    torsoDecalType: 'diver-gauge',
    faceType: 'classic-smile'
  },
  'scientist-minifig': {
    id: 'scientist-minifig',
    name: 'Scientist Minifig',
    skinColor: '#F7CA18',
    headgearType: 'scientist-hair',
    headgearColor: '#94A3B8',
    torsoColor: '#F8FAFC',
    armColor: '#F8FAFC',
    handColor: '#38BDF8',
    hipsColor: '#475569',
    legsColor: '#334155',
    torsoDecalType: 'lab-coat',
    faceType: 'classic-smile'
  },
  'pilot-minifig': {
    id: 'pilot-minifig',
    name: 'Pilot Minifig',
    skinColor: '#F7CA18',
    headgearType: 'pilot-cap',
    headgearColor: '#1E293B',
    headgearAccentColor: '#F59E0B',
    torsoColor: '#0F172A',
    armColor: '#1E293B',
    handColor: '#F7CA18',
    hipsColor: '#0F172A',
    legsColor: '#1E293B',
    torsoDecalType: 'pilot-wings',
    faceType: 'pilot-aviators'
  },
  'artist-minifig': {
    id: 'artist-minifig',
    name: 'Artist Minifig',
    skinColor: '#F7CA18',
    headgearType: 'artist-beret',
    headgearColor: '#1E293B',
    torsoColor: '#F1F5F9',
    armColor: '#1E3A8A',
    handColor: '#F7CA18',
    hipsColor: '#1E3A8A',
    legsColor: '#2563EB',
    torsoDecalType: 'artist-splatters',
    faceType: 'samurai-mustache'
  },
  'viking-minifig': {
    id: 'viking-minifig',
    name: 'Viking Minifig',
    skinColor: '#F7CA18',
    headgearType: 'viking-horns',
    headgearColor: '#71717A',
    headgearAccentColor: '#F1F5F9',
    torsoColor: '#78350F',
    armColor: '#92400E',
    handColor: '#F7CA18',
    hipsColor: '#451A03',
    legsColor: '#78350F',
    torsoDecalType: 'viking-harness',
    faceType: 'king-beard'
  },
  'dragon-minifig': {
    id: 'dragon-minifig',
    name: 'Dragon Minifig',
    skinColor: '#F7CA18',
    headgearType: 'dragon-hood',
    headgearColor: '#B91C1C',
    headgearAccentColor: '#F59E0B',
    torsoColor: '#991B1B',
    armColor: '#B91C1C',
    handColor: '#B91C1C',
    hipsColor: '#7F1D1D',
    legsColor: '#991B1B',
    torsoDecalType: 'dragon-belly',
    faceType: 'ninja-focus',
    accessoryType: 'dragon-wings'
  },
  'farmer-minifig': {
    id: 'farmer-minifig',
    name: 'Farmer Minifig',
    skinColor: '#F7CA18',
    headgearType: 'straw-hat',
    headgearColor: '#FDE047',
    headgearAccentColor: '#CA8A04',
    torsoColor: '#DC2626',
    armColor: '#DC2626',
    handColor: '#F7CA18',
    hipsColor: '#1D4ED8',
    legsColor: '#2563EB',
    torsoDecalType: 'farmer-overalls',
    faceType: 'freckles'
  },
  'alien-minifig': {
    id: 'alien-minifig',
    name: 'Alien Minifig',
    skinColor: '#4ADE80',
    headgearType: 'alien-cranium',
    headgearColor: '#22C55E',
    headgearAccentColor: '#15803D',
    torsoColor: '#7E22CE',
    armColor: '#9333EA',
    handColor: '#4ADE80',
    hipsColor: '#6B21A8',
    legsColor: '#7E22CE',
    feetColor: '#22C55E',
    torsoDecalType: 'alien-galaxy',
    faceType: 'alien-eyes'
  },
  'miner-minifig': {
    id: 'miner-minifig',
    name: 'Miner Minifig',
    skinColor: '#F7CA18',
    headgearType: 'miner-hard-hat',
    headgearColor: '#EAB308',
    headgearAccentColor: '#38BDF8',
    torsoColor: '#EA580C',
    armColor: '#C2410C',
    handColor: '#475569',
    hipsColor: '#334155',
    legsColor: '#475569',
    torsoDecalType: 'miner-harness',
    faceType: 'soot-smudge'
  },
  'princess-minifig': {
    id: 'princess-minifig',
    name: 'Princess Minifig',
    skinColor: '#F7CA18',
    headgearType: 'princess-tiara',
    headgearColor: '#F59E0B',
    headgearAccentColor: '#FDE047',
    torsoColor: '#F472B6',
    armColor: '#F472B6',
    handColor: '#F7CA18',
    hipsColor: '#DB2777',
    legsColor: '#EC4899',
    torsoDecalType: 'princess-bodice',
    faceType: 'princess-lashes'
  }
};

export const getMinifigureTheme = (id: string): MinifigureTheme =>
  MINIFIGURE_THEMES[id] ?? DEFAULT_MINIFIGURE_THEME;
